markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]
title : Henry Sztul
production_url : http://hsztul.github.io
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: henryaym
analytics:
gauges:
author :
  name : Henry Sztul
  github : hsztul
  twitter : sztul
  email: henry@sztul.com
